name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push images
        run: |
          docker login \
            --username ${{ secrets.USERNAME }} \
            --password ${{ secrets.PASSWORD }}
          echo Conc: $(nproc)
          make -j$(nproc) push
