name: Build

on:
  push:
    branches: [ master ]
    paths: [ Dockerfile ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push images
        run: |
          echo Conc: $(nproc)
          make -j$(nproc) push
